config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'splash#index'
  resources :contracts
  resources :groups, only: %i[index show new create] do
    resources :purchases, only: %i[index new create]
  end

  root 'splash#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :purchase
  belongs_to :group
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /contracts or /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1 or /contracts/1.json
  def show; end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit; end

  # POST /contracts or /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to contract_url(@contract), notice: 'Contract was successfully created.' }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1 or /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to contract_url(@contract), notice: 'Contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1 or /contracts/1.json
  def destroy
    @contract.destroy

    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contract
    @contract = Contract.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contract_params
    params.require(:contract).permit(:purchase_id, :group_id)
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_contract.html.erb
<div id="<%= dom_id contract %>">
  <p>
    <strong>Purchase:</strong>
    <%= contract.purchase_id %>
  </p>

  <p>
    <strong>Group:</strong>
    <%= contract.group_id %>
  </p>

</div>

app/views/contracts/_form.html.erb
<%= form_with(model: contract) do |form| %>
  <% if contract.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
        <% contract.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :purchase_id, style: "display: block" %>
    <%= form.text_field :purchase_id %>
  </div>

  <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.text_field :group_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing contract</h1>

<%= render "form", contract: @contract %>

<br>

<div>
  <%= link_to "Show this contract", @contract %> |
  <%= link_to "Back to contracts", contracts_path %>
</div>

app/views/contracts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contracts</h1>

<div id="contracts">
  <% @contracts.each do |contract| %>
    <%= render contract %>
    <p>
      <%= link_to "Show this contract", contract %>
    </p>
  <% end %>
</div>

<%= link_to "New contract", new_contract_path %>

app/views/contracts/new.html.erb
<h1>New contract</h1>

<%= render "form", contract: @contract %>

<br>

<div>
  <%= link_to "Back to contracts", contracts_path %>
</div>

app/views/contracts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contract %>

<div>
  <%= link_to "Edit this contract", edit_contract_path(@contract) %> |
  <%= link_to "Back to contracts", contracts_path %>

  <%= button_to "Destroy this contract", @contract, method: :delete %>
</div>