config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'splash#index'
  resources :contracts
  resources :groups, only: %i[index show new create] do
    resources :purchases, only: %i[index new create]
  end

  root 'splash#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :contracts, dependent: :destroy
  has_many :purchases, through: :contracts, dependent: :destroy
  # has_and_belongs_to_many :purchases, optional: true

  validates :name, presence: true
  def sum_total
    contracts.includes([:purchase])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
    @purchases = @group.group_purchases
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = current_user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    # @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="form-layout">
<%= form_with model: @group, method: :post, local: true, scope: :group do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "input-field" %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
     <%= form.select :icon, ["👔", "🎵", "🎟️", "🏆", "⚽", "🎮", "🎭", "🎨", "🎉", "🚗", "✈️", "🚢", "🚌", "🚊", "💈", "⛺", "🏨", "🏥", "🏗️​", "🏭", "🏖️", "🍽️", "🍼", "🥂", "🍔", "🍧", "🐕‍🦺​", "👩‍👧‍👧", "👨‍👩‍👧‍👦​", "🤖"], class: "input-field" %>
  </div>

    
  <div>
    <%= form.submit class: 'btn' %>
  </div>
<% end %>
<div>

app/views/groups/_group.html.erb
<li id="<%= dom_id group %>" class="group-list">

  <div class="img">
    <%= group.icon %>
   </div>

  <div class="mid list-mid">
    <div>
      <h3><%=link_to group.name, group_purchases_path(group.id) %></h3>
      <span>20 Apr 2010</span>
    </div>
    <div>
      <span>Total: <%= group.sum_total.sum(:amount) %></span>
    </div>

    <%
=begin%>
 <%=button_to 'Delete', group_path(group.id), method: :delete %> 
<%
=end%>
  </div>

</li>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<ul id="groups" class="group">
<% if @groups.empty?%>
   <h2>Please add Categories</h2>
  <%else%>
 
   <% @groups.each do |group| %>
    <%= render group %>
  
  <% end %>
  <%end%>
<div class='footer-btn'>
  <%= link_to "add category", new_group_path %>
  </div>
</ul>

app/views/groups/new.html.erb
<div class='form-container'>
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>
<% @purchases.each do | purchase | %>

<%=  purchase.name%>
<%end%>
<%
=begin%>
 
<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div> 
<%
=end%>