config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'splash#index'
  resources :contracts
  resources :groups, only: %i[index show new create] do
    resources :purchases, only: %i[index new create]
  end

  root 'splash#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /purchases or /purchases.json
  def index
    # @purchases = Purchase.all

    @group = Group.find(params[:group_id])
    @purchases = @group.purchases.order('created_at DESC')
    @total = @purchases.sum(:amount)
  end

  # GET /purchases/1 or /purchases/1.json
  def show; end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit; end

  # POST /purchases or /purchases.json
  def create
    @group = Group.find(params[:group_id])
    @purchase = current_user.purchases.new(purchase_params)
    respond_to do |format|
      if @purchase.save
        set_contract(@group.id, @purchase.id)
        format.html { redirect_to group_purchases_url(@group), notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1 or /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to purchase_url(@purchase), notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1 or /purchases/1.json
  def destroy
    @purchase.destroy

    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_purchase
    @purchase = Purchase.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def purchase_params
    params.require(:purchase).permit(:name, :amount)
  end

  def set_contract(group, purchase)
    Contract.create(group_id: group, purchase_id: purchase)
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.erb
<div class="form-layout">
<%= form_with(url: group_purchases_path, model: @purchase, method: :post, local: true, scope: :purchase) do |form| %>
  <% if purchase.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% purchase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name,  class: "input-field" %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount, step: 1, placeholder: "amount", required: true, class: "input-field" %>
  </div>

 <div>
    <%= form.submit class: 'btn' %>
  </div>
<% end %>
</div>

app/views/purchases/_purchase.html.erb
<li id="<%= dom_id purchase %>" class="group-list border">
<div class="list-mid p-mid">
  <div class="name-div">
    <h3><%= purchase.name %></h3>
  </div>

  <div class="amount-div">
   <span> <strong>Amount:</strong></span>
    <span><%= purchase.amount %><span>
  </div>
</div>
</li>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render "form", purchase: @purchase %>

<br>

<div>
  <%= link_to "Show this purchase", @purchase %> |
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/index.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "back", groups_path %>


<div class="total">
<span>Total: <%= @total%></span>
</div>

<ul id="purchases" class="group">
  <% @purchases.each do |purchase| %>
    <%= render purchase %>
    
  <% end %>
  <div class='footer-btn tran-foot'>
  <%= link_to "add new Transaction", new_group_purchase_path %>
  </div>
</ul>

app/views/purchases/new.html.erb
<div class="form-container">
<h1>New purchase</h1>

<%= render "form", purchase: @purchase %>

<br>

<div>
  <%= link_to "Back to purchases", group_purchases_path %>
</div>
</div>

app/views/purchases/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @purchase %>

<div>
  <%= link_to "Edit this purchase", edit_purchase_path(@purchase) %> |
  <%= link_to "Back to purchases", purchases_path %>

  <%= button_to "Destroy this purchase", @purchase, method: :delete %>
</div>